name: mailpit
icon: mailpit
type: service
title: Mailpit
options:
- version: '1.20'
  tag: v1.20
endpoints:
- name: mailpit
  ports:
  - name: smtp
    number: 1025
    protocol: tcp
  - name: ui
    number: 8025
    protocol: http
labels:
- mailpit
- smtpd

volumes:
- name: data
  title: Data
  optional: true
  helm:
    labels: persistence.labels
    values:
    - name: persistence.enabled
      value: true
    - name: persistence.size
      value: '{{volumes.data.size}}Gi'
    # mandatory to use existing claim since this volume will have import function
    # we will mount different claim after import and doing it through sts's volumeclaimtemplates is not supported
# disabled due to missing imports (required for this to work – we create PVC manually instead of using volumeClaimTemplate)    
#    - name: persistence.existingClaim
#      value: '{{volumes.data.claim}}'

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/mailpit
  chart: oci://registry-1.docker.io/wodby/mailpit
  version: 0.2.0

workloads:
- id: main
  kind: statefulset
  primary: true
  helm:
    labels: podLabels
    annotations: podAnnotations
    volumes: extraVolumes
  containers:
  - name: mailpit
    image: axllent/mailpit
    helm:
      resources: resources
      env: envVars
      mounts: extraVolumeMounts
